function Generate{
    param (
        $Folder
    )

    $result = ";//THIS FILE WAS GENERATED BY CODEGEN`n";
    cd $Folder;
    $names = Get-ChildItem | Select-Object -ExpandProperty Name;
    $array = "module.exports = [";
    foreach ($i in $names) {
        $varname = $i.split(".")[0];
        $require = "const " + $varname + " = require('./"+ $Folder +"/" + $i + "');";
        $array += $varname + "," ;
        $result += $require + "`n";
    }
    $array = $array.Substring(0,$array.Length-1);
    $array += "];";
    cd ..;
    $result += "`n`n" + $array;

    Write-Output $result
}

$c = Generate -Folder 'commands';
$t = Generate -Folder 'triggers';
Out-File -Encoding utf8 -FilePath .\gen_commands.js -InputObject $c
Out-File -Encoding utf8 -FilePath .\gen_triggers.js -InputObject $t