;//THIS FILE WAS GENERATED BY CODEGEN
const black = require('./commands/black.js');
const cardSearch = require('./commands/cardSearch.js');
const cardSearch_small = require('./commands/cardSearch_small.js');
const control = require('./commands/control.js');
const fang = require('./commands/fang.js');
const hello = require('./commands/hello.js');
const ihor = require('./commands/ihor.js');
const kalitas = require('./commands/kalitas.js');
const kamaz = require('./commands/kamaz.js');
const lotus = require('./commands/lotus.js');
const pizda = require('./commands/pizda.js');
const rakdos = require('./commands/rakdos.js');
const rating = require('./commands/rating.js');
const registration = require('./commands/registration.js');
const ring = require('./commands/ring.js');


module.exports = [black,cardSearch,cardSearch_small,control,fang,hello,ihor,kalitas,kamaz,lotus,pizda,rakdos,rating,registration,ring];
