;//THIS FILE WAS GENERATED BY CODEGEN
import black from './commands/black.js';
import cardSearch from './commands/cardSearch.js';
import cardSearch_small from './commands/cardSearch_small.js';
import control from './commands/control.js';
import fang from './commands/fang.js';
import hello from './commands/hello.js';
import ihor from './commands/ihor.js';
import kalitas from './commands/kalitas.js';
import kamaz from './commands/kamaz.js';
import lotus from './commands/lotus.js';
import pizda from './commands/pizda.js';
import rakdos from './commands/rakdos.js';
import rating from './commands/rating.js';
import registration from './commands/registration.js';
import ring from './commands/ring.js';
import rozklad from './commands/rozklad.js';
import ternopil from './commands/ternopil.js';
import vitalii from './commands/vitalii.js';


export default [black,cardSearch,cardSearch_small,control,fang,hello,ihor,kalitas,kamaz,lotus,pizda,rakdos,rating,registration,ring,rozklad,ternopil,vitalii];
