;//THIS FILE WAS GENERATED BY CODEGEN
import black from './commands/black';
import cardSearch from './commands/cardSearch';
import cardSearch_small from './commands/cardSearch_small';
import control from './commands/control';
import fang from './commands/fang';
import hello from './commands/hello';
import ihor from './commands/ihor';
import kalitas from './commands/kalitas';
import kamaz from './commands/kamaz';
import lotus from './commands/lotus';
import pizda from './commands/pizda';
import potuzhno from './commands/potuzhno';
import potuzhnoStats from './commands/potuzhnoStats';
import rakdos from './commands/rakdos';
import rating from './commands/rating';
import registration from './commands/registration';
import ring from './commands/ring';
import rozklad from './commands/rozklad';
import slon from './commands/slon';
import ternopil from './commands/ternopil';
import vitalii from './commands/vitalii';


export default [black,cardSearch,cardSearch_small,control,fang,hello,ihor,kalitas,kamaz,lotus,pizda,potuzhno,potuzhnoStats,rakdos,rating,registration,ring,rozklad,slon,ternopil,vitalii].filter(x => x.active);
